export const WRITING_BATCH_1_KEYS = [
  'executive_summary', 'account_snapshot', 'account_fit_score',
  'buying_committee', 'pain_hypotheses', 'why_now',
  'value_proposition', 'competitive_landscape', 'cultural_context',
] as const

export const WRITING_BATCH_2_KEYS = [
  'deal_motion', 'personalized_sequences', 'discovery_guide',
  'demo_strategy', 'battle_cards', 'pilot_design',
  'roi_model', 'deal_execution_plan', 'appendix',
] as const

export interface PlaybookContext {
  playbookId: string
  productName: string
  productDescription: string
  valuePropositions: string[]
  targetCompany: string
  industry: string
  geography: string
  priorityTier: string
  productUrl?: string
  competitors?: string[]
  deploymentModel?: string
  dealSize?: string
  salesCycle?: string
}

export interface WritingContext extends PlaybookContext {
  approvedContacts: {
    name: string
    title: string
    company: string
    linkedin_url?: string
    confidence: string
    rationale?: string
  }[]
}

export function buildResearchPrompt(ctx: PlaybookContext): string {
  return [
    `# ABM PLAYBOOK RESEARCH — Phase 1`,
    ``,
    `## Your Task`,
    `Research the target account and identify key buying committee contacts.`,
    ``,
    `## CRITICAL RULES — READ CAREFULLY`,
    `- DO NOT call any external APIs or HTTP endpoints.`,
    `- DO NOT use curl, fetch, or any network tools to update application state.`,
    `- DO NOT write to any files or databases directly.`,
    `- Your ONLY output must be a single JSON block at the end of your response.`,
    `- The JSON must match the exact schema defined below.`,
    ``,
    `## Product`,
    `Name: ${ctx.productName}`,
    `URL: ${ctx.productUrl ?? 'N/A'}`,
    `Description: ${ctx.productDescription}`,
    `Value Propositions:`,
    ...ctx.valuePropositions.map(v => `  - ${v}`),
    `Competitors: ${ctx.competitors?.join(', ') ?? 'N/A'}`,
    `Deployment: ${ctx.deploymentModel ?? 'SaaS'}`,
    `Deal Size: ${ctx.dealSize ?? 'N/A'}`,
    `Sales Cycle: ${ctx.salesCycle ?? 'N/A'}`,
    ``,
    `## Target Account`,
    `Company: ${ctx.targetCompany}`,
    `Industry: ${ctx.industry}`,
    `Geography: ${ctx.geography}`,
    `Priority: ${ctx.priorityTier}`,
    ``,
    `## Research Instructions`,
    `1. Research ${ctx.targetCompany} thoroughly using web search and available sources.`,
    `2. Identify 5-8 key buying committee contacts relevant to ${ctx.productName}.`,
    `3. For each contact: find their name, title, LinkedIn URL, and why they matter.`,
    `4. Gather company intelligence: recent news, signals, technology stack, strategic priorities.`,
    `5. Compile source URLs for all factual claims.`,
    ``,
    `## Required Output Format`,
    `End your response with a JSON block using EXACTLY this schema:`,
    ``,
    `\`\`\`json`,
    `{`,
    `  "phase": "research",`,
    `  "status": "contact_review",`,
    `  "progress_pct": 60,`,
    `  "agent_status": "Contacts ready for review",`,
    `  "contacts": [`,
    `    {`,
    `      "name": "Full Name",`,
    `      "title": "Job Title",`,
    `      "company": "${ctx.targetCompany}",`,
    `      "linkedin_url": "https://linkedin.com/in/...",`,
    `      "email": null,`,
    `      "rationale": "Why this person matters for the deal",`,
    `      "source_urls": ["https://..."],`,
    `      "confidence": "high"`,
    `    }`,
    `  ],`,
    `  "sources": [`,
    `    {`,
    `      "url": "https://...",`,
    `      "title": "Source Title",`,
    `      "publisher": "Publisher Name",`,
    `      "note": "What this source tells us",`,
    `      "confidence": "high"`,
    `    }`,
    `  ]`,
    `}`,
    `\`\`\``,
    ``,
    `All data must be real and specific to ${ctx.targetCompany}. No placeholder data.`,
  ].join('\n')
}

export function buildWritingPrompt(ctx: WritingContext): string {
  const contactsSummary = ctx.approvedContacts
    .map(c => `- ${c.name} (${c.title}) — ${c.rationale ?? 'Key decision maker'}`)
    .join('\n')

  return [
    `# ABM PLAYBOOK WRITING — Phase 2`,
    ``,
    `## Your Task`,
    `Write all 18 sections of a hyper-personalized ABM playbook for ${ctx.targetCompany}.`,
    `Every section must be deeply researched, specific, and actionable — NOT generic.`,
    ``,
    `## CRITICAL RULES — READ CAREFULLY`,
    `- DO NOT call any external APIs or HTTP endpoints.`,
    `- DO NOT use curl, fetch, or any network tools to update application state.`,
    `- DO NOT write to any files or databases directly.`,
    `- Your ONLY output must be a single JSON block at the end of your response.`,
    `- The JSON must match the exact schema defined below.`,
    ``,
    `## Context`,
    `### Product: ${ctx.productName}`,
    `Description: ${ctx.productDescription}`,
    `Value Props: ${ctx.valuePropositions.join('; ')}`,
    `Competitors: ${ctx.competitors?.join(', ') ?? 'N/A'}`,
    `Deployment: ${ctx.deploymentModel ?? 'SaaS'} | Deal Size: ${ctx.dealSize ?? 'N/A'} | Sales Cycle: ${ctx.salesCycle ?? 'N/A'}`,
    ``,
    `### Target Account: ${ctx.targetCompany}`,
    `Industry: ${ctx.industry} | Geography: ${ctx.geography} | Priority: ${ctx.priorityTier}`,
    ``,
    `### Approved Contacts`,
    contactsSummary,
    ``,
    `## Section Keys and Required Content (all 18 must be present)`,
    ``,
    `1. executive_summary`,
    `   - 3-4 paragraph strategic overview: why this account, why now, recommended approach`,
    `   - Key signals discovered, top 3 risks, and recommended next action`,
    ``,
    `2. account_snapshot`,
    `   - Company overview: size, revenue, HQ, key locations, employee count`,
    `   - Recent financials and growth trajectory (with sources)`,
    `   - Current technology stack relevant to the deal (HR tech, data infrastructure, etc.)`,
    `   - Strategic priorities from annual reports, earnings calls, or press releases`,
    `   - Org structure and key divisions`,
    ``,
    `3. account_fit_score`,
    `   - Score the account 0–10 across these dimensions using a markdown table:`,
    `     | Dimension | Score (0-10) | Evidence | Notes |`,
    `     Dimensions: Budget Authority, Recognized Need, Urgency/Timeline, Strategic Fit,`,
    `     Champion Potential, Technical Fit, Competitive Exposure, Deal Complexity`,
    `   - Overall fit score (weighted average), tier recommendation (Tier 1 / 2 / 3)`,
    `   - One-paragraph investment rationale`,
    ``,
    `4. buying_committee`,
    `   - Full table of each contact: Name | Title | Role in deal | Pain points | Personalization angle`,
    `   - Influence map (economic buyer, technical evaluator, champion, end user, blocker)`,
    `   - Org chart in markdown showing reporting relationships`,
    `   - For each person: what they care about, how to approach them, key phrases to use/avoid`,
    ``,
    `5. pain_hypotheses`,
    `   - 5–7 specific pain hypotheses based on research evidence`,
    `   - For each: Pain statement | Evidence (sourced) | Implication | How ${ctx.productName} solves it`,
    `   - Rank by severity and likelihood`,
    `   - Include a "proof of pain" section with direct quotes or signals found in research`,
    ``,
    `6. why_now`,
    `   - 4–6 time-sensitive trigger events with dates and sources (funding rounds, leadership changes,`,
    `     regulatory deadlines, competitive threats, product launches, earnings calls)`,
    `   - For each event: what happened, why it creates urgency, how to reference it in outreach`,
    `   - Overall "why now" narrative connecting all signals`,
    ``,
    `7. value_proposition`,
    `   - Value proposition mapped to each approved contact/persona`,
    `   - For each persona: Core message | Business outcome | Proof point | ROI estimate`,
    `   - Differentiated value vs. competitors (what only ${ctx.productName} can deliver)`,
    `   - 3 headline messages the account will remember`,
    ``,
    `8. competitive_landscape`,
    `   - Table: Competitor | Current position at account | Strengths | Weaknesses | Displacement angle`,
    `   - Which competitor is most likely incumbent and why`,
    `   - Landmine questions (questions to ask that expose competitor weaknesses)`,
    `   - Our unfair advantages in this specific account context`,
    ``,
    `9. cultural_context`,
    `   - Communication norms for ${ctx.geography} (formality level, meeting etiquette, decision-making style)`,
    `   - Industry-specific norms for ${ctx.industry}`,
    `   - Regulatory or compliance context that affects the deal`,
    `   - Language/tone dos and don'ts for outreach`,
    `   - Preferred communication channels in this market`,
    ``,
    `10. deal_motion`,
    `    - Recommended channel mix (email, LinkedIn, phone, events, executive outreach)`,
    `    - Entry point strategy: who to contact first and why`,
    `    - Multi-threaded plan: how to build relationships across the buying committee in parallel`,
    `    - Sequencing: week-by-week engagement plan for the first 30 days`,
    `    - Escalation triggers: when to bring in executives, SEs, or partners`,
    ``,
    `11. personalized_sequences`,
    `    - For EACH approved contact, write a COMPLETE outreach sequence:`,
    `      EMAIL SEQUENCE (5 emails per contact):`,
    `        Email 1 (Day 1): Subject line + full body — account signal hook, single CTA`,
    `        Email 2 (Day 4): Subject line + full body — value-led, different angle`,
    `        Email 3 (Day 8): Subject line + full body — social proof / case study`,
    `        Email 4 (Day 14): Subject line + full body — pain hypothesis + question`,
    `        Email 5 (Day 21): Subject line + full body — breakup / last attempt`,
    `      LINKEDIN SEQUENCE (per contact):`,
    `        Connection request note (300 char max)`,
    `        Follow-up message after connect`,
    `        InMail if not connected`,
    `      PHONE VOICEMAIL SCRIPT (per contact, 30 seconds)`,
    `    - Every message must reference specific signals from research (NOT generic templates)`,
    `    - Tone must match the contact's seniority and ${ctx.geography} cultural norms`,
    ``,
    `12. discovery_guide`,
    `    - 15–20 discovery questions organized by theme:`,
    `      Current State (4–5 questions) | Pain Depth (4–5 questions) |`,
    `      Impact & Priority (3–4 questions) | Decision Process (3–4 questions)`,
    `    - For each question: the question itself, what to listen for, follow-up probes`,
    `    - "Trap" questions that differentiate our approach from competitors`,
    `    - Discovery call structure: opening → exploration → hypothesis testing → close for next step`,
    ``,
    `13. demo_strategy`,
    `    - Which 3–4 product capabilities to lead with for this specific account and why`,
    `    - Demo narrative: tell the account's story using our product as the solution`,
    `    - Persona-specific demo tracks: what to emphasize for each stakeholder in the room`,
    `    - "Wow moment" to engineer and when to deploy it`,
    `    - Likely demo objections and how to handle them live`,
    `    - Required prep: what data/integrations to have set up before the demo`,
    ``,
    `14. battle_cards`,
    `    - One battle card per likely competitor (2–3 cards minimum)`,
    `    - Each card: Competitor name | Their pitch | Our counter | Proof points | Trap questions`,
    `    - Top 5 objections we'll hear from this account (based on persona research) + rebuttals`,
    `    - Objection format: Objection | Why they're really saying it | Response | Proof`,
    ``,
    `15. pilot_design`,
    `    - Recommended pilot scope: which team, which use case, how long (4–8 weeks typical)`,
    `    - Success criteria table: Metric | Baseline | Target | How to measure`,
    `    - Stakeholders required for pilot approval (who signs off, who participates)`,
    `    - Week-by-week pilot timeline with milestones`,
    `    - Expansion path: how pilot success converts to full deal`,
    ``,
    `16. roi_model`,
    `    - Business case with estimated numbers specific to ${ctx.targetCompany}'s scale`,
    `    - Cost of inaction (what it costs them NOT to solve this problem per year)`,
    `    - ROI table: Investment | Year 1 return | Year 2 return | Year 3 return | Payback period`,
    `    - Key assumptions (state them explicitly with sources)`,
    `    - Soft benefits beyond hard ROI (risk reduction, strategic advantage, etc.)`,
    `    - One-page executive summary narrative for the CFO / economic buyer`,
    ``,
    `17. deal_execution_plan`,
    `    - Milestone gates: Discovery → Demo → Technical Validation → Pilot → Proposal → Close`,
    `    - For each milestone: owner, success criteria, estimated timeline, dependencies`,
    `    - Week 1–4 action plan (specific daily/weekly tasks for the rep)`,
    `    - Executive alignment strategy: when and how to bring in your C-suite`,
    `    - Risk register: top 3 deal risks and mitigation actions`,
    `    - Mutual action plan template for sharing with the champion`,
    ``,
    `18. appendix`,
    `    - Raw research notes and additional company background`,
    `    - Technology stack details and integration considerations`,
    `    - Additional contacts identified but not approved (for reference)`,
    `    - Methodology notes and data confidence ratings`,
    ``,
    `## Global Writing Instructions`,
    `- Every section must be specific to ${ctx.targetCompany} — zero generic filler.`,
    `- Reference approved contacts by name throughout the playbook.`,
    `- Use markdown formatting: ## headers, ### sub-headers, tables, bullet lists.`,
    `- For every factual claim, include (source: URL) inline citation.`,
    `- Cultural context and tone must match ${ctx.geography} norms throughout.`,
    `- Minimum content per section: 300 words. Sections 11 (sequences) and 16 (ROI) should be 800+ words.`,
    ``,
    `## Required Output Format`,
    `End your response with a JSON block using EXACTLY this schema:`,
    ``,
    `\`\`\`json`,
    `{`,
    `  "phase": "writing",`,
    `  "status": "complete",`,
    `  "progress_pct": 100,`,
    `  "agent_status": "Playbook complete",`,
    `  "sections": [`,
    `    {`,
    `      "section_key": "executive_summary",`,
    `      "title": "Executive Summary",`,
    `      "content_markdown": "## Overview\\n\\n...",`,
    `      "order_index": 1,`,
    `      "sources": [`,
    `        {`,
    `          "url": "https://...",`,
    `          "title": "Source",`,
    `          "publisher": "Publisher",`,
    `          "claim": "The specific claim this supports",`,
    `          "confidence": "high"`,
    `        }`,
    `      ]`,
    `    }`,
    `  ]`,
    `}`,
    `\`\`\``,
    ``,
    `All 18 sections must be present. Content must be specific to ${ctx.targetCompany}.`,
  ].join('\n')
}

// ─── Per-section writing instructions (shared between full prompt and batches) ───

function sectionInstructions(ctx: WritingContext): Record<string, string[]> {
  return {
    executive_summary: [
      `3-4 paragraph strategic overview: why this account, why now, recommended approach`,
      `Key signals discovered, top 3 risks, and recommended next action`,
    ],
    account_snapshot: [
      `Company overview: size, revenue, HQ, key locations, employee count`,
      `Recent financials and growth trajectory (with sources)`,
      `Current technology stack relevant to the deal`,
      `Strategic priorities from annual reports, earnings calls, or press releases`,
    ],
    account_fit_score: [
      `Score the account 0–10 across these dimensions using a markdown table:`,
      `| Dimension | Score (0-10) | Evidence | Notes |`,
      `Dimensions: Budget Authority, Recognized Need, Urgency/Timeline, Strategic Fit, Champion Potential, Technical Fit, Competitive Exposure, Deal Complexity`,
      `Overall fit score (weighted average), tier recommendation, one-paragraph investment rationale`,
    ],
    buying_committee: [
      `Full table: Name | Title | Role in deal | Pain points | Personalization angle`,
      `Influence map (economic buyer, technical evaluator, champion, end user, blocker)`,
      `Org chart in markdown showing reporting relationships`,
      `For each person: what they care about, how to approach them, key phrases to use/avoid`,
    ],
    pain_hypotheses: [
      `5–7 specific pain hypotheses based on research evidence`,
      `For each: Pain statement | Evidence (sourced) | Implication | How ${ctx.productName} solves it`,
      `Rank by severity and likelihood`,
      `"Proof of pain" section with direct quotes or signals found in research`,
    ],
    why_now: [
      `4–6 time-sensitive trigger events with dates and sources`,
      `For each event: what happened, why it creates urgency, how to reference it in outreach`,
      `Overall "why now" narrative connecting all signals`,
    ],
    value_proposition: [
      `Value proposition mapped to each approved contact/persona`,
      `For each persona: Core message | Business outcome | Proof point | ROI estimate`,
      `Differentiated value vs. competitors — what only ${ctx.productName} can deliver`,
      `3 headline messages the account will remember`,
    ],
    competitive_landscape: [
      `Table: Competitor | Current position at account | Strengths | Weaknesses | Displacement angle`,
      `Which competitor is most likely incumbent and why`,
      `Landmine questions that expose competitor weaknesses`,
      `Our unfair advantages in this specific account context`,
    ],
    cultural_context: [
      `Communication norms for ${ctx.geography} (formality level, meeting etiquette, decision-making style)`,
      `Industry-specific norms for ${ctx.industry}`,
      `Regulatory or compliance context that affects the deal`,
      `Language/tone dos and don'ts; preferred communication channels in this market`,
    ],
    deal_motion: [
      `Recommended channel mix (email, LinkedIn, phone, events, executive outreach)`,
      `Entry point strategy: who to contact first and why`,
      `Multi-threaded plan: how to build relationships across the buying committee in parallel`,
      `Sequencing: week-by-week engagement plan for the first 30 days`,
      `Escalation triggers: when to bring in executives, SEs, or partners`,
    ],
    personalized_sequences: [
      `For EACH approved contact, write a COMPLETE outreach sequence:`,
      `EMAIL SEQUENCE (5 emails per contact):`,
      `  Email 1 (Day 1): Subject line + full body — account signal hook, single CTA`,
      `  Email 2 (Day 4): Subject line + full body — value-led, different angle`,
      `  Email 3 (Day 8): Subject line + full body — social proof / case study`,
      `  Email 4 (Day 14): Subject line + full body — pain hypothesis + question`,
      `  Email 5 (Day 21): Subject line + full body — breakup / last attempt`,
      `LINKEDIN SEQUENCE (per contact): Connection request note + follow-up + InMail`,
      `PHONE VOICEMAIL SCRIPT (per contact, 30 seconds)`,
      `Every message must reference specific signals — NOT generic templates`,
    ],
    discovery_guide: [
      `15–20 discovery questions organized by theme:`,
      `Current State (4–5) | Pain Depth (4–5) | Impact & Priority (3–4) | Decision Process (3–4)`,
      `For each question: the question, what to listen for, follow-up probes`,
      `"Trap" questions that differentiate our approach from competitors`,
      `Discovery call structure: opening → exploration → hypothesis testing → close for next step`,
    ],
    demo_strategy: [
      `Which 3–4 product capabilities to lead with for this specific account and why`,
      `Demo narrative: tell the account's story using ${ctx.productName} as the solution`,
      `Persona-specific demo tracks for each stakeholder`,
      `"Wow moment" to engineer and when to deploy it`,
      `Likely demo objections and live handling; required prep before demo`,
    ],
    battle_cards: [
      `One battle card per likely competitor (2–3 cards minimum)`,
      `Each card: Competitor name | Their pitch | Our counter | Proof points | Trap questions`,
      `Top 5 objections from this account + rebuttals`,
      `Format: Objection | Why they're really saying it | Response | Proof`,
    ],
    pilot_design: [
      `Recommended pilot scope: which team, use case, duration (4–8 weeks)`,
      `Success criteria table: Metric | Baseline | Target | How to measure`,
      `Stakeholders required for pilot approval (who signs off, who participates)`,
      `Week-by-week pilot timeline with milestones; expansion path post-pilot`,
    ],
    roi_model: [
      `Business case with estimated numbers specific to ${ctx.targetCompany}'s scale`,
      `Cost of inaction (what it costs them NOT to solve this problem per year)`,
      `ROI table: Investment | Year 1 return | Year 2 return | Year 3 return | Payback period`,
      `Key assumptions stated explicitly with sources`,
      `Soft benefits beyond hard ROI; one-page CFO/economic buyer executive narrative`,
    ],
    deal_execution_plan: [
      `Milestone gates: Discovery → Demo → Technical Validation → Pilot → Proposal → Close`,
      `For each milestone: owner, success criteria, estimated timeline, dependencies`,
      `Week 1–4 action plan (specific daily/weekly tasks for the rep)`,
      `Executive alignment strategy; risk register: top 3 risks + mitigation`,
      `Mutual action plan template for sharing with the champion`,
    ],
    appendix: [
      `Raw research notes and additional company background`,
      `Technology stack details and integration considerations`,
      `Additional contacts identified but not approved (for reference)`,
      `Methodology notes and data confidence ratings`,
    ],
  }
}

/**
 * Build a writing prompt for a subset of sections (batch mode).
 * Split writing across two calls to stay within model output token limits.
 */
export function buildWritingPromptBatch(
  ctx: WritingContext,
  batchKeys: readonly string[],
  batchNum: 1 | 2,
): string {
  const contactsSummary = ctx.approvedContacts
    .map(c => `- ${c.name} (${c.title}) — ${c.rationale ?? 'Key decision maker'}`)
    .join('\n')

  const instructions = sectionInstructions(ctx)
  const sectionLines: string[] = []
  batchKeys.forEach((key, idx) => {
    const globalOrder = batchNum === 1 ? idx + 1 : idx + 10
    sectionLines.push(`${globalOrder}. ${key}`)
    const lines = instructions[key] ?? []
    lines.forEach(l => sectionLines.push(`   - ${l}`))
    sectionLines.push('')
  })

  const batchDesc = batchNum === 1
    ? `BATCH 1 of 2 — Sections 1–9 (Research + Positioning)`
    : `BATCH 2 of 2 — Sections 10–18 (Outreach + Execution)`

  const batchNote = batchNum === 2
    ? `NOTE: This is Batch 2. Sections 1–9 are already written. Be consistent with that content.`
    : ''

  return [
    `# ABM PLAYBOOK WRITING — Phase 2 (${batchDesc})`,
    ``,
    ...(batchNote ? [`## ${batchNote}`, ``] : []),
    `## Your Task`,
    `Write the ${batchKeys.length} assigned sections of the ABM playbook for ${ctx.targetCompany}.`,
    `Every section must be deeply researched, specific, and actionable — NOT generic.`,
    ``,
    `## CRITICAL RULES — READ CAREFULLY`,
    `- DO NOT call any external APIs or HTTP endpoints.`,
    `- DO NOT use curl, fetch, or any network tools to update application state.`,
    `- DO NOT write to any files or databases directly.`,
    `- Your ONLY output must be a single JSON block at the end of your response.`,
    `- The JSON must match the exact schema defined below.`,
    ``,
    `## Context`,
    `### Product: ${ctx.productName}`,
    `Description: ${ctx.productDescription}`,
    `Value Props: ${ctx.valuePropositions.join('; ')}`,
    `Competitors: ${ctx.competitors?.join(', ') ?? 'N/A'}`,
    `Deployment: ${ctx.deploymentModel ?? 'SaaS'} | Deal Size: ${ctx.dealSize ?? 'N/A'} | Sales Cycle: ${ctx.salesCycle ?? 'N/A'}`,
    ``,
    `### Target Account: ${ctx.targetCompany}`,
    `Industry: ${ctx.industry} | Geography: ${ctx.geography} | Priority: ${ctx.priorityTier}`,
    ``,
    `### Approved Contacts`,
    contactsSummary,
    ``,
    `## Sections to Write (${batchKeys.length} sections)`,
    ``,
    ...sectionLines,
    `## Global Writing Instructions`,
    `- Every section must be specific to ${ctx.targetCompany} — zero generic filler.`,
    `- Reference approved contacts by name throughout.`,
    `- Use markdown formatting: ## headers, ### sub-headers, tables, bullet lists.`,
    `- For every factual claim, include (source: URL) inline citation.`,
    `- Cultural context and tone must match ${ctx.geography} norms throughout.`,
    `- Minimum 300 words per section. personalized_sequences and roi_model should be 800+ words.`,
    ``,
    `## Required Output Format`,
    `End your response with a JSON block using EXACTLY this schema:`,
    ``,
    `\`\`\`json`,
    `{`,
    `  "phase": "writing",`,
    `  "status": "complete",`,
    `  "progress_pct": ${batchNum === 1 ? 80 : 100},`,
    `  "agent_status": "Batch ${batchNum} complete",`,
    `  "sections": [`,
    `    {`,
    `      "section_key": "${batchKeys[0]}",`,
    `      "title": "Section Title",`,
    `      "content_markdown": "## Overview\\n\\n...",`,
    `      "order_index": ${batchNum === 1 ? 1 : 10},`,
    `      "sources": [`,
    `        {`,
    `          "url": "https://...",`,
    `          "title": "Source",`,
    `          "publisher": "Publisher",`,
    `          "claim": "The specific claim this supports",`,
    `          "confidence": "high"`,
    `        }`,
    `      ]`,
    `    }`,
    `  ]`,
    `}`,
    `\`\`\``,
    ``,
    `All ${batchKeys.length} assigned sections must be present. Content must be specific to ${ctx.targetCompany}.`,
  ].join('\n')
}
