import {
  MockPlaybook,
  PlaybookStatus,
  ContactVerificationStatus,
  QualityCheckStatus,
  SectionStatus,
} from '@/types'

const MOCK_PLAYBOOK_ID = 'pb_belfius_fintech_2025'
const MOCK_USER_ID = 'usr_demo_001'

export const mockPlaybook: MockPlaybook = {
  id: MOCK_PLAYBOOK_ID,
  user_id: MOCK_USER_ID,
  product_name: 'FinFlow AI',
  product_url: 'https://finflowai.com',
  product_brief: {
    product_name: 'FinFlow AI',
    description:
      'AI-powered treasury management and cash flow forecasting platform for European banks. Reduces FX exposure by 40% and automates reconciliation across multi-currency portfolios.',
    value_propositions: [
      'Reduce FX exposure by up to 40% with predictive hedging',
      'Automate 85% of treasury reconciliation workflows',
      'Real-time cash visibility across 50+ currencies',
      'Regulatory reporting auto-generation (MiFID II, Basel III)',
    ],
    target_personas: [
      'Group CFO / Treasurer',
      'Head of Treasury Technology',
      'Chief Risk Officer',
      'VP Finance Operations',
    ],
    differentiators: [
      'Only solution with native Belgian/EU regulatory compliance built-in',
      'AI trained on 10M+ European banking transactions',
      '90-day time to value vs 18-month industry average',
      'Pre-built SWIFT integration — no middleware required',
    ],
    competitors: ['Kyriba', 'TreasuryXpress', 'ION Treasury', 'SAP Treasury'],
    deployment_model: 'saas',
    deal_size: '€250K–€800K ARR',
    sales_cycle: '6–12 months',
  },
  target_company: 'Belfius Bank',
  target_url: 'https://belfius.be',
  industry: 'Financial Services',
  geography: 'Belgium / BeNeLux',
  priority_tier: 'tier1',
  status: 'complete' as PlaybookStatus,
  progress_pct: 100,
  agent_status: [
    {
      agent: 'orchestrator',
      task: 'Coordinating research and generation pipeline',
      status: 'complete',
      completed_at: '2025-03-12T09:45:00Z',
    },
    {
      agent: 'researcher',
      task: 'Deep account research — Belfius digital transformation signals',
      status: 'complete',
      completed_at: '2025-03-12T11:20:00Z',
    },
    {
      agent: 'writer',
      task: 'Generating hyper-personalized outreach sequences',
      status: 'complete',
      completed_at: '2025-03-12T13:15:00Z',
    },
    {
      agent: 'reviewer',
      task: '16-point quality verification',
      status: 'complete',
      completed_at: '2025-03-12T14:00:00Z',
    },
  ],
  created_at: '2025-03-12T09:00:00Z',
  updated_at: '2025-03-12T14:00:00Z',
  sections: [
    {
      id: 'sec_001',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'executive_summary',
      title: 'Executive Summary',
      content: `## Strategic Opportunity\n\nBelfius Bank is in the midst of its "Belfius 2030" digital transformation programme, having committed €500M to technology modernisation through 2027. The treasury function — currently running on a fragmented mix of legacy Murex modules and manual Excel workflows — is a critical dependency for this transformation.\n\n**Primary Trigger:** Belfius announced a €2.3B covered bond issuance in Q1 2025, exposing significant gaps in their multi-currency cash management capabilities. CFO Dirk Gyselinck publicly cited "treasury visibility" as a top-3 finance priority in the March 2025 annual report.\n\n**Why FinFlow AI Wins Here:** Our native Belgian regulatory compliance engine (including NBB reporting automation) eliminates the #1 objection for Belgian banks: "We'll need to customise everything for local regulations." We are the only vendor with a pre-certified NBB integration.\n\n**Recommended Approach:** Warm introduction via Karel Bogaert (Belfius CIO, connects to FinFlow board advisor Jan De Cock) → CFO-level executive briefing → Treasury technology pilot on Belgian subsidiary FX book.`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:00:00Z',
    },
    {
      id: 'sec_002',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'account_intelligence',
      title: 'Account Intelligence Dossier',
      content: `## Belfius Bank — Company Profile\n\n**Headquarters:** Brussels, Belgium\n**Revenue:** €3.1B (FY2024)\n**Employees:** 7,400\n**Assets Under Management:** €285B\n**Ownership:** Belgian state (100%)\n\n### Recent Strategic Signals\n\n| Signal | Date | Relevance Score |\n|--------|------|-----------------|\n| "Belfius 2030" digital transformation announced | Jan 2024 | 🔴 Critical |\n| €500M technology investment committed | Jan 2024 | 🔴 Critical |\n| Hired 3 new treasury technologists from ING Belgium | Feb 2025 | 🔴 Critical |\n| Q1 2025 covered bond issuance (€2.3B) | Mar 2025 | 🟠 High |\n| CFO Gyselinck speech at Belgian Finance Forum | Feb 2025 | 🟠 High |\n| Published sustainability bond framework update | Dec 2024 | 🟡 Medium |\n\n### Technology Stack (Research-Verified)\n- **Core Banking:** Temenos T24 (migrating to Temenos Transact)\n- **Treasury:** Legacy Murex + Excel (TARGET FOR DISPLACEMENT)\n- **ERP:** SAP S/4HANA (partial rollout)\n- **Data Platform:** Azure Data Lake (Microsoft partnership)\n- **Identity:** Microsoft Entra ID\n\n### Pain Points Confirmed Via LinkedIn + Job Postings\n1. "Senior Treasury Analyst" posting (Feb 2025) mentions "manual FX reconciliation" — 3 open roles\n2. Head of Finance Ops posted about "SWIFT integration challenges" in industry forum\n3. 2024 annual report notes €12M in FX hedging costs — above peer benchmark`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:05:00Z',
    },
    {
      id: 'sec_003',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'buying_committee',
      title: 'Buying Committee & Org Map',
      content: `## Decision-Making Unit\n\n### Economic Buyer\n**Dirk Gyselinck — Group CFO**\n- LinkedIn: linkedin.com/in/dirk-gyselinck-belfius\n- Decision authority: Final sign-off on deals >€200K\n- Primary pain: Treasury visibility, regulatory reporting burden\n- Communication style: Data-driven, formal, prefers written executive summaries\n- Key relationship: Sits on board of Belgian Finance Federation with FinFlow's advisor Jan De Cock\n\n### Technical Buyer\n**Karel Bogaert — Chief Information Officer**\n- LinkedIn: linkedin.com/in/karel-bogaert-belfius\n- Decision authority: Technology architecture approval\n- Primary pain: Legacy system integration complexity\n- Key insight: Publicly endorsed Microsoft Azure-first strategy — FinFlow's Azure-native deployment is a strong fit\n\n### Champion (Target)\n**Sophie Vandermeersch — Head of Treasury Technology**\n- LinkedIn: linkedin.com/in/sophie-vandermeersch\n- Most likely internal champion — owns the treasury transformation mandate\n- Background: 8 years at Euroclear, treasury systems specialist\n- Reach approach: Direct LinkedIn outreach with industry peer credibility\n\n### End User Influencer\n**Marc Declercq — VP Finance Operations**\n- LinkedIn: linkedin.com/in/marc-declercq-belfius\n- Day-to-day pain owner (manual reconciliation, FX exposure)\n- Can become a vocal internal advocate if shown time savings`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:10:00Z',
    },
    {
      id: 'sec_004',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'why_now',
      title: '"Why Now" Signal Analysis',
      content: `## Urgency Drivers — Why Act in Q2 2025\n\n### Primary Trigger: Board-Level Treasury Mandate\nThe Belfius 2030 transformation plan explicitly names "treasury and liquidity management modernisation" as a 2025 deliverable. The window to engage is **before the RFP process begins** (estimated Q3 2025 based on procurement cycle analysis).\n\n### Signal Stack\n\n**Signal 1 — Covered Bond Issuance (CRITICAL)**\nThe €2.3B issuance in Q1 2025 requires cross-currency cash management across EUR, USD, GBP. Current Murex setup cannot handle real-time netting at this scale. This is an active, burning pain point.\n\n**Signal 2 — 3 Open Treasury Technology Roles**\nBelfius has posted "Senior Treasury Analyst" and "Treasury Systems Engineer" roles in February 2025. This signals they're trying to solve the problem with headcount — an opportunity to reframe: hire 3 people OR buy FinFlow AI.\n\n**Signal 3 — NBB Regulatory Update (May 2025)**\nThe National Bank of Belgium is implementing updated liquidity reporting requirements effective May 2025. Belfius will need compliant reporting by Q3. FinFlow's pre-certified NBB module removes this risk immediately.\n\n**Signal 4 — CFO Forum Speech**\nDirective Gyselinck's speech at the Belgian Finance Forum (Feb 2025) explicitly mentioned "treasury as a strategic enabler, not a back-office function." This signals budget receptivity at the CFO level.\n\n### Recommended Timing\n- **Week of April 14:** Initial outreach to Sophie Vandermeersch (champion)\n- **Late April:** CFO-level executive briefing request\n- **May:** Proof of concept proposal before NBB deadline anxiety peaks\n- **Q3:** Formal evaluation / RFP response`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:15:00Z',
    },
    {
      id: 'sec_005',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'personalized_sequences',
      title: 'Hyper-Personalized Outreach Sequences',
      content: `## Sequence A: Sophie Vandermeersch (Champion)\n### Email 1 — Peer Credibility Hook\n\n**Subject:** Belfius treasury transformation — a parallel to what Euroclear solved\n\n> Sophie,\n>\n> Your work at Euroclear on the TARGET2-Securities integration gave you a front-row seat to what multi-currency reconciliation complexity looks like at scale. Belfius is now navigating a similar inflection point — the €2.3B covered bond issuance is exposing the limits of legacy Murex at volume.\n>\n> I'm reaching out because we've helped two Belgian banks (KBC and Argenta — happy to connect you with their treasury heads) cut FX reconciliation time by 80% within 90 days, without replacing their core banking stack.\n>\n> Would a 20-minute call make sense? I can share the KBC case study which maps closely to Belfius's multi-entity EUR/USD structure.\n>\n> Best,\n> [Your Name]\n\n---\n\n## Sequence B: Dirk Gyselinck (CFO / Economic Buyer)\n### Email 1 — Board-Level Framing\n\n**Subject:** Treasury as a strategic asset — a question for Belfius\n\n> Dirk,\n>\n> Your framing at the Belgian Finance Forum — "treasury as a strategic enabler" — resonated with us deeply. Most CFOs we speak with still treat treasury as a cost centre. The ones who've shifted that framing are generating measurable alpha from their cash positions.\n>\n> Belfius's Belfius 2030 programme has an opportunity here that most Belgian banks are missing: converting the treasury modernisation mandate into a competitive advantage, not just a compliance exercise.\n>\n> I'd value 30 minutes to share what two of your Belgian peers have discovered. Jan De Cock mentioned you're the right person to have this conversation with.\n>\n> Best regards,\n> [Your Name]\n\n---\n\n## LinkedIn Sequence: Karel Bogaert (CIO)\n### Message 1 — Technical Peer Credibility\n\n> Karel, I noticed Belfius's Azure-first commitment in the 2024 report — very aligned with where the market is heading. We've built FinFlow AI natively on Azure (not a lift-and-shift) and recently completed a deployment at a Belgian bank that ran entirely within their existing Microsoft infrastructure. No new security perimeter, no new vendor relationships. Worth 15 minutes?`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:20:00Z',
    },
    {
      id: 'sec_006',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'cultural_context',
      title: 'Cultural & Regulatory Context',
      content: `## Belgium — Doing Business Context\n\n### Communication Norms\n- **Language:** Belfius operates in Dutch, French, and English. Brussels HQ contacts are bilingual (FR/NL). Use English for written communication; offer materials in both languages if requested.\n- **Formality:** Belgian business culture is formal and relationship-oriented. Do NOT use first names until invited. "Monsieur Gyselinck" or "Mr. Bogaert" in initial contact.\n- **Decision Speed:** Belgian financial institutions have consensual decision-making — expect multiple stakeholders to be involved. Budget 3–4 months for the evaluation phase.\n- **Trust Building:** Peer references from Belgian institutions carry extreme weight. KBC and Argenta references are gold here.\n\n### Regulatory Landscape\n- **NBB (National Bank of Belgium):** Primary regulator. Any vendor touching treasury systems needs NBB approval pathway. FinFlow's pre-certified status is a significant differentiator.\n- **FSMA:** Belgian securities regulator — relevant for bond issuance treasury operations.\n- **MiFID II:** EU-wide, already in compliance.\n- **Belgian State Ownership:** As a state-owned bank, Belfius has procurement requirements including competitive tendering for contracts >€215K. Plan for a formal RFP process.\n\n### Cultural Sensitivities\n- Belfius is politically sensitive as a state bank — avoid any messaging about "disruption" or challenging Belgian institutions\n- Emphasise "partnership" and "Belgian roots" (our EU headquarters in Amsterdam helps)\n- Belgian privacy norms are strict — do not reference specific personal contact information in outreach`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:25:00Z',
    },
    {
      id: 'sec_007',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'battle_cards',
      title: 'Battle Cards & Objection Handling',
      content: `## Objection 1: "We're already evaluating Kyriba"\n\n**When they say:** "We've had conversations with Kyriba and they seem to cover our requirements."\n\n**Our response:** "Kyriba is a strong product for US-headquartered multinationals. The challenge Belgian banks consistently tell us is that Kyriba's NBB reporting module requires 6–9 months of customisation — they've built for US GAAP, not Belgian GAAP or NBB liquidity reporting. We're certified out of the box, which is how KBC went live in 90 days. Would it be useful to see a side-by-side of the Belgian compliance coverage?"\n\n---\n\n## Objection 2: "We have a budget freeze"\n\n**When they say:** "IT spend is constrained through Q2."\n\n**Our response:** "We hear this often, and it's why we structure our pilots differently. The NBB regulatory deadline in May creates a specific window — and our observation is that treasury modernisation often unlocks its own budget through FX cost reduction. At KBC, the first-year savings covered 60% of the FinFlow license cost. Would it help if we modelled what that looks like for Belfius's current FX book?"\n\n---\n\n## Objection 3: "Our Murex system is being upgraded"\n\n**When they say:** "We're already investing in a Murex upgrade."\n\n**Our response:** "That's actually a very common pairing — 4 of our top 10 European bank clients run FinFlow alongside Murex. We don't replace Murex; we sit above it as the intelligence and reporting layer. Your Murex upgrade handles execution; FinFlow handles visibility, forecasting, and regulatory reporting. They're complementary, not competitive."`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:30:00Z',
    },
    {
      id: 'sec_008',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'measurement_framework',
      title: 'Measurement Framework',
      content: `## Success Metrics & KPIs\n\n### Phase 1: Proof of Concept (Days 1–90)\n| Metric | Baseline | Target | How Measured |\n|--------|----------|--------|---------------|\n| FX reconciliation time | 4.5 hours/day | <1 hour/day | System logs |\n| Forecast accuracy (7-day) | 68% | >85% | Back-testing |\n| Manual report generation | 12 hours/month | 0 hours | Time tracking |\n| NBB report prep time | 3 days | 4 hours | Finance team survey |\n\n### Phase 2: Full Deployment (Months 4–12)\n| Metric | Target | \n|--------|--------|\n| FX hedging cost reduction | 25–40% |\n| Cash visibility completeness | 95%+ |\n| Multi-currency accounts covered | 100% |\n| Regulatory reports automated | MiFID II, NBB, Basel III |\n\n### Business Case Summary\n- **Current FX hedging cost:** ~€12M/year (per annual report)\n- **Projected savings at 35% reduction:** €4.2M/year\n- **FinFlow AI annual cost:** €350K–€500K\n- **ROI:** 8–12x in Year 1\n- **Payback period:** 3–4 months`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:35:00Z',
    },
    {
      id: 'sec_009',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'content_strategy',
      title: 'Content Asset Strategy',
      content: `## Content Assets to Create / Deploy\n\n### For Sophie Vandermeersch (Champion)\n1. **KBC Case Study (PDF):** "How KBC Treasury Cut FX Reconciliation Time by 80% in 90 Days" — Focus on technical integration, timeline, and team impact\n2. **Technical Architecture Brief:** FinFlow + Temenos T24 integration guide (1-pager)\n3. **ROI Calculator:** Interactive spreadsheet personalised to Belfius's FX book size\n\n### For Dirk Gyselinck (CFO)\n1. **Executive Brief (2 pages):** "Treasury as Strategic Alpha: The Belgian Bank Opportunity"\n2. **Benchmark Report:** Belfius treasury costs vs. Belgian peer benchmarks (sourced from public annual reports)\n\n### For Karel Bogaert (CIO)\n1. **Azure Architecture Diagram:** FinFlow deployment within Azure infrastructure\n2. **Security & Compliance Brief:** SOC 2 Type II + NBB certification documentation\n\n### For the RFP Stage\n1. **Full Vendor Response Template:** Pre-built RFP response for Belgian bank requirements\n2. **Pilot Proposal:** 90-day proof of concept scoped specifically to Belfius's FX book`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:40:00Z',
    },
    {
      id: 'sec_010',
      playbook_id: MOCK_PLAYBOOK_ID,
      section_type: 'appendix',
      title: 'Appendix',
      content: `## Research Sources & Confidence Scores\n\n| Claim | Source | Confidence |\n|-------|--------|------------|\n| €500M technology investment | Belfius 2024 Annual Report, p.47 | HIGH |\n| CFO Gyselinck treasury statement | Belgian Finance Forum recording, Feb 2025 | HIGH |\n| 3 open treasury roles | Belfius LinkedIn page, verified March 2025 | HIGH |\n| Murex deployment details | LinkedIn posts from Belfius technology team | MEDIUM |\n| Karel Bogaert Azure commitment | Belfius Tech Blog post, Jan 2025 | HIGH |\n| Jan De Cock board connection | LinkedIn mutual connections [UNVERIFIED — needs verification] | LOW |\n| KBC reference availability | CRM database — confirm before using | MEDIUM |\n\n## Glossary\n- **NBB:** Nationale Bank van Belgie / Banque Nationale de Belgique\n- **FSMA:** Financial Services and Markets Authority\n- **T24:** Temenos T24 core banking system\n- **MiFID II:** Markets in Financial Instruments Directive II\n- **UDR Loop:** Universal Deep Research loop (internal agent methodology)`,
      status: 'reviewed' as SectionStatus,
      created_at: '2025-03-12T13:45:00Z',
    },
  ],
  contacts: [
    {
      id: 'con_001',
      playbook_id: MOCK_PLAYBOOK_ID,
      name: 'Dirk Gyselinck',
      title: 'Group Chief Financial Officer',
      linkedin_url: 'https://linkedin.com/in/dirk-gyselinck-belfius',
      confidence: 'high',
      source: 'Belfius Annual Report 2024 + LinkedIn',
      verification_status: 'confirmed' as ContactVerificationStatus,
      email: 'd.gyselinck@belfius.be',
      notes: 'Decision authority for deals >€200K. Connect via Jan De Cock introduction.',
      created_at: '2025-03-12T11:30:00Z',
    },
    {
      id: 'con_002',
      playbook_id: MOCK_PLAYBOOK_ID,
      name: 'Karel Bogaert',
      title: 'Chief Information Officer',
      linkedin_url: 'https://linkedin.com/in/karel-bogaert-belfius',
      confidence: 'high',
      source: 'Belfius Tech Blog + LinkedIn',
      verification_status: 'confirmed' as ContactVerificationStatus,
      email: 'k.bogaert@belfius.be',
      notes: 'Azure-first champion. Key technical gatekeeper.',
      created_at: '2025-03-12T11:35:00Z',
    },
    {
      id: 'con_003',
      playbook_id: MOCK_PLAYBOOK_ID,
      name: 'Sophie Vandermeersch',
      title: 'Head of Treasury Technology',
      linkedin_url: 'https://linkedin.com/in/sophie-vandermeersch',
      confidence: 'high',
      source: 'LinkedIn + Belfius org chart research',
      verification_status: 'confirmed' as ContactVerificationStatus,
      email: 's.vandermeersch@belfius.be',
      notes: 'Primary champion target. Euroclear background. Most reachable entry point.',
      created_at: '2025-03-12T11:40:00Z',
    },
    {
      id: 'con_004',
      playbook_id: MOCK_PLAYBOOK_ID,
      name: 'Marc Declercq',
      title: 'VP Finance Operations',
      linkedin_url: 'https://linkedin.com/in/marc-declercq-belfius',
      confidence: 'medium',
      source: 'LinkedIn search + job posting cross-reference',
      verification_status: 'needs_review' as ContactVerificationStatus,
      email: undefined,
      notes: 'End-user pain owner. Email not verified — needs manual confirmation.',
      created_at: '2025-03-12T11:45:00Z',
    },
    {
      id: 'con_005',
      playbook_id: MOCK_PLAYBOOK_ID,
      name: 'Isabelle Renard',
      title: 'Head of Regulatory Affairs',
      linkedin_url: 'https://linkedin.com/in/isabelle-renard-belfius',
      confidence: 'medium',
      source: 'Belgian Finance Federation member directory',
      verification_status: 'pending' as ContactVerificationStatus,
      email: undefined,
      notes: 'Key for NBB compliance angle. Title needs verification.',
      created_at: '2025-03-12T11:50:00Z',
    },
  ],
  quality_checks: [
    { id: 'qc_01', playbook_id: MOCK_PLAYBOOK_ID, check_number: 1, check_name: 'All contacts have verified names, titles, and LinkedIn URLs', category: 'Accuracy', status: 'pass' as QualityCheckStatus, details: '5/5 contacts have verified LinkedIn URLs. 3/5 emails confirmed.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_02', playbook_id: MOCK_PLAYBOOK_ID, check_number: 2, check_name: 'No generic outreach — every sequence references specific account signals', category: 'Personalization', status: 'pass' as QualityCheckStatus, details: 'All sequences reference specific signals: covered bond issuance, Belfius 2030, NBB deadline.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_03', playbook_id: MOCK_PLAYBOOK_ID, check_number: 3, check_name: '"Why Now" signals are recent (within 90 days) and specific', category: 'Relevance', status: 'pass' as QualityCheckStatus, details: 'All 4 primary signals are dated Q1 2025. NBB regulatory deadline confirmed for May 2025.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_04', playbook_id: MOCK_PLAYBOOK_ID, check_number: 4, check_name: 'Cultural adaptation matches target geography + industry', category: 'Cultural Fit', status: 'pass' as QualityCheckStatus, details: 'Belgian communication norms documented. Dutch/French language awareness included. State bank sensitivities noted.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_05', playbook_id: MOCK_PLAYBOOK_ID, check_number: 5, check_name: 'Competitive landscape identifies actual incumbents, not generic competitors', category: 'Accuracy', status: 'pass' as QualityCheckStatus, details: 'Kyriba confirmed as active evaluation. Murex identified as incumbent via employee LinkedIn data.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_06', playbook_id: MOCK_PLAYBOOK_ID, check_number: 6, check_name: 'Battle cards address real objections, not straw-man arguments', category: 'Quality', status: 'pass' as QualityCheckStatus, details: '3 objections sourced from 2025 Belgian banking deals in CRM. Murex upgrade objection verified.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_07', playbook_id: MOCK_PLAYBOOK_ID, check_number: 7, check_name: 'Every email has a clear CTA appropriate to the persona and stage', category: 'Effectiveness', status: 'pass' as QualityCheckStatus, details: 'Champion sequence: discovery call. CFO sequence: executive briefing. All CTAs are low-friction.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_08', playbook_id: MOCK_PLAYBOOK_ID, check_number: 8, check_name: 'Tone matches the target\'s industry norms (formal vs. casual)', category: 'Cultural Fit', status: 'pass' as QualityCheckStatus, details: 'All sequences use formal Belgian business register. No first names in initial contact.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_09', playbook_id: MOCK_PLAYBOOK_ID, check_number: 9, check_name: 'No fabricated data — all claims are sourced or marked [UNVERIFIED]', category: 'Integrity', status: 'warn' as QualityCheckStatus, details: 'Jan De Cock board connection marked [UNVERIFIED] in appendix. Needs manual verification before use in outreach.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_10', playbook_id: MOCK_PLAYBOOK_ID, check_number: 10, check_name: 'Buying committee covers all key roles', category: 'Completeness', status: 'pass' as QualityCheckStatus, details: 'Economic buyer (CFO), technical buyer (CIO), champion (Head Treasury Tech), end user (VP Finance Ops) — all covered.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_11', playbook_id: MOCK_PLAYBOOK_ID, check_number: 11, check_name: 'Measurement framework has realistic KPIs for the sales cycle length', category: 'Practicality', status: 'pass' as QualityCheckStatus, details: 'KPIs phased across 90-day POC and 12-month deployment. ROI model uses public FX cost data.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_12', playbook_id: MOCK_PLAYBOOK_ID, check_number: 12, check_name: 'Content assets are actionable with specific topics, not vague briefs', category: 'Specificity', status: 'pass' as QualityCheckStatus, details: '8 content assets specified with exact scope and audience.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_13', playbook_id: MOCK_PLAYBOOK_ID, check_number: 13, check_name: 'Org chart reflects current reporting structure', category: 'Accuracy', status: 'pass' as QualityCheckStatus, details: 'Verified against Belfius 2024 annual report org structure. All titles confirmed via LinkedIn.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_14', playbook_id: MOCK_PLAYBOOK_ID, check_number: 14, check_name: "Outreach strategy accounts for the target's preferred communication channels", category: 'Cultural Fit', status: 'pass' as QualityCheckStatus, details: 'Belgian banking: email preferred for CFO-level; LinkedIn for technology leaders. Warm intro pathway documented.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_15', playbook_id: MOCK_PLAYBOOK_ID, check_number: 15, check_name: 'No internal inconsistencies between sections', category: 'Consistency', status: 'pass' as QualityCheckStatus, details: 'Cross-referenced all sections. Consistent messaging on NBB compliance, Azure fit, and Murex coexistence.', created_at: '2025-03-12T13:50:00Z' },
    { id: 'qc_16', playbook_id: MOCK_PLAYBOOK_ID, check_number: 16, check_name: 'All sources cited with confidence scores', category: 'Transparency', status: 'pass' as QualityCheckStatus, details: 'Appendix contains full source table with HIGH/MEDIUM/LOW confidence scores.', created_at: '2025-03-12T13:50:00Z' },
  ],
}

// Additional mock playbooks for dashboard
export const mockPlaybooks: MockPlaybook[] = [
  mockPlaybook,
  {
    id: 'pb_ing_saas_2025',
    user_id: MOCK_USER_ID,
    product_name: 'FinFlow AI',
    product_url: 'https://finflowai.com',
    product_brief: mockPlaybook.product_brief,
    target_company: 'ING Belgium',
    target_url: 'https://ing.be',
    industry: 'Financial Services',
    geography: 'Belgium',
    priority_tier: 'tier1',
    status: 'generating' as PlaybookStatus,
    progress_pct: 72,
    agent_status: [
      { agent: 'orchestrator', task: 'Managing generation pipeline', status: 'running', detail: 'Orchestrating writer agent' },
      { agent: 'researcher', task: 'Account research complete', status: 'complete', completed_at: '2025-03-13T10:00:00Z' },
      { agent: 'writer', task: 'Writing personalized email sequences', status: 'running', detail: 'Sequence 3 of 5' },
      { agent: 'reviewer', task: 'Awaiting content', status: 'pending' },
    ],
    created_at: '2025-03-13T08:00:00Z',
    updated_at: '2025-03-13T11:30:00Z',
    sections: [],
    contacts: [],
    quality_checks: [],
  },
  {
    id: 'pb_bnp_2025',
    user_id: MOCK_USER_ID,
    product_name: 'FinFlow AI',
    product_url: 'https://finflowai.com',
    product_brief: mockPlaybook.product_brief,
    target_company: 'BNP Paribas Fortis',
    target_url: 'https://bnpparibasfortis.be',
    industry: 'Financial Services',
    geography: 'Belgium / France',
    priority_tier: 'tier2',
    status: 'contact_review' as PlaybookStatus,
    progress_pct: 45,
    agent_status: [
      { agent: 'orchestrator', task: 'Waiting on contact review', status: 'pending' },
      { agent: 'researcher', task: 'Research complete', status: 'complete', completed_at: '2025-03-11T14:00:00Z' },
      { agent: 'writer', task: 'Waiting', status: 'pending' },
      { agent: 'reviewer', task: 'Waiting', status: 'pending' },
    ],
    created_at: '2025-03-11T09:00:00Z',
    updated_at: '2025-03-11T14:30:00Z',
    sections: [],
    contacts: [],
    quality_checks: [],
  },
]

export const mockProfile = {
  id: 'prof_001',
  user_id: MOCK_USER_ID,
  email: 'demo@finflowai.com',
  name: 'Alex Laurent',
  plan: 'growth' as const,
  playbooks_used: 3,
  created_at: '2025-01-15T00:00:00Z',
}
